import turtle as trtl

painter = trtl.Turtle()

painter.pensize(5)
painter.turtlesize(5)
painter.color('red')
painter.forward(100)
painter.penup()
painter.right(100)
painter.pendown()
painter.circle(150)
painter.color('green')
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50)
painter.color('blue')
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50)
painter.color('yellow')
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50)
painter.color('magenta')
painter.penup()
painter.back(150)
painter.pendown()
painter.circle(50)
painter.color('cyan')
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50)
painter.color('magenta')
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50)


wn = trtl.Screen()
wn.mainloop()


